export default 
  [
    {
      _id: "1",
      name: "Australia",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/51qxYm5NXrL.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "2",
      name: "Chile",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/91j-JTFhm0L.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Columbia",
      category: "book",
      image:
        "https://images-na.ssl-images-amazon.com/images/I/718TnurkpEL._AC_UL200_SR200,200_.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "4",
      name: "Denmark",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/51sOghHa5nL.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "5",
      name: "England",
      category: "book",
      image:
        "https://lonelyplanet-weblinc.netdna-ssl.com/product_images/lonely_planet_us/england-travel-guide-10/pdp/5c9a147c6c80950a7baa9f73/pdp_main.jpg?c=1553601660",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "6",
      name: "Finland",
      category: "book",
      image:
        "https://images-na.ssl-images-amazon.com/images/I/51J5Ox0OKsL._SX322_BO1,204,203,200_.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "7",
      name: "France",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/814kgi01l8L.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "8",
      name: "Germany",
      category: "book",
      image:
        "https://images-na.ssl-images-amazon.com/images/I/51ZEihZAatL._SX322_BO1,204,203,200_.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "9",
      name: "Honduras",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/512kn2cFU-L.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "10",
      name: "India",
      category: "book",
      image:
        "https://www.a5travelbooks.com/uploads/1/2/0/7/12079777/lonely-planet-india_orig.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "11",
      name: "Ireland",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/51Xj4wMAhpL.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "12",
      name: "Lybia",
      category: "book",
      image: "https://s1.dmcdn.net/v/3G6WO1H4R6ZttHqq_/x480",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "13",
      name: "Morocco",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/71IaELWkOqL.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "14",
      name: "New Zealand",
      category: "book",
      image: "https://images-na.ssl-images-amazon.com/images/I/71eUV2Z2XxL.jpg",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
    {
      _id: "15",
      name: "Russia",
      category: "book",
      image:
        "https://lonelyplanet-weblinc.netdna-ssl.com/product_images/lonely_planet_us/russia-travel-guide-8/pdp/5a996525d860885921060144/pdp_main.jpg?c=1520002418",
      price: 60,
      rating: 5,
      reviews: 10,
      countInStock: 5,
    },
  ];

